import { DESKTOP } from "../lib/mode";

/**
 * Embeds the standalone paper-wiki graph viewer (paper-wiki/viz.html,
 * generated by the paper-wiki-manager skill) rather than re-implementing its
 * force-directed graph natively. The viewer is self-contained (data + the
 * fcose/cytoscape libraries are baked into the HTML) and stays independently
 * usable outside os-ui — see os-ui/DESIGN.md for why this app is an iframe.
 */
export function PaperWikiPage() {
  return (
    <iframe
      // The desktop client serves the viewer on its own origin, away from the
      // app's endpoints and bridge (os-ui/client/DESIGN.md §3.2).
      src={DESKTOP ? "app://paper-wiki/viz.html" : "./paper-wiki/viz.html"}
      title="Paper Wiki"
      className="h-full w-full border-0"
    />
  );
}
