/**
 * Embeds the standalone paper-wiki graph viewer (paper-wiki/viz.html,
 * generated by the paper-wiki-manager skill) rather than re-implementing its
 * force-directed graph natively. The viewer is self-contained (data + the
 * fcose/cytoscape libraries are baked into the HTML) and stays independently
 * usable outside os-ui — see os-ui/DESIGN.md for why this app is an iframe.
 */
export function PaperWikiPage() {
  return (
    <iframe
      src="/paper-wiki/viz.html"
      title="Paper Wiki"
      className="h-full w-full border-0"
    />
  );
}
